// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWxg_YNMMgBAsHVnP72PLMbUVyvsTgZmA',
    appId: '1:746817370558:web:6698cf89e74c15d7c1e1ef',
    messagingSenderId: '746817370558',
    projectId: 'email-app-9defa',
    authDomain: 'email-app-9defa.firebaseapp.com',
    storageBucket: 'email-app-9defa.appspot.com',
    measurementId: 'G-S5ND6JHQKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhCsu-4tDjUST8QpSt4Lrico-J1N_vGPo',
    appId: '1:746817370558:android:427642d93004527ac1e1ef',
    messagingSenderId: '746817370558',
    projectId: 'email-app-9defa',
    storageBucket: 'email-app-9defa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5FA2TlMGieSiYi45CS6JY3f59rPgIz4A',
    appId: '1:746817370558:ios:0826b3d01ea30305c1e1ef',
    messagingSenderId: '746817370558',
    projectId: 'email-app-9defa',
    storageBucket: 'email-app-9defa.appspot.com',
    iosClientId: '746817370558-717b6k94i2d017vdtc1tll0k878id4j8.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5FA2TlMGieSiYi45CS6JY3f59rPgIz4A',
    appId: '1:746817370558:ios:0826b3d01ea30305c1e1ef',
    messagingSenderId: '746817370558',
    projectId: 'email-app-9defa',
    storageBucket: 'email-app-9defa.appspot.com',
    iosClientId: '746817370558-717b6k94i2d017vdtc1tll0k878id4j8.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyDWxg_YNMMgBAsHVnP72PLMbUVyvsTgZmA",
    authDomain: "email-app-9defa.firebaseapp.com",
    projectId: "email-app-9defa",
    storageBucket: "email-app-9defa.appspot.com",
    messagingSenderId: "746817370558",
    appId: "1:746817370558:web:cb1bd3f577c390b6c1e1ef",
    measurementId: "G-N10WPVQ1PE"
  );

}